<script lang="ts">
	import { tick } from 'svelte';
	import gsap from 'gsap';
	import { panel, closePanel } from '$lib/stores/ui.svelte.js';
	import { setFocus, focus } from '$lib/stores/scene.svelte.js';
	import ContactForm from './ContactForm.svelte';

	let panelEl: HTMLDivElement;
	let shareCopied = $state(false);

	function handleClose() {
		setFocus(null);
		closePanel();
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') handleClose();
	}

	function handleShare() {
		const url = `${window.location.origin}${window.location.pathname}?focus=${focus.key}`;
		navigator.clipboard.writeText(url).then(() => {
			shareCopied = true;
			setTimeout(() => { shareCopied = false; }, 2000);
		});
	}

	$effect(() => {
		if (panel.open) {
			tick().then(() => {
				if (!panelEl) return;
				const items = panelEl.querySelectorAll(
					'.panel-card, .skill-group, .facts li, .contact-panel li, .available-badge'
				);
				if (items.length === 0) return;
				gsap.fromTo(items,
					{ y: 18, opacity: 0 },
					{ y: 0, opacity: 1, duration: 0.38, stagger: 0.065, ease: 'power2.out', clearProps: 'all' }
				);
			});
		}
	});
</script>

<svelte:window on:keydown={handleKeydown} />

<div
	bind:this={panelEl}
	class="panel"
	class:open={panel.open}
	role="dialog"
	aria-modal="true"
	aria-label={panel.content?.title ?? 'Detail panel'}
	aria-hidden={!panel.open}
>
	<div class="panel-header">
		<h2 class="panel-title">{panel.content?.title ?? ''}</h2>
		<div class="panel-actions">
			{#if focus.key}
				<button class="panel-share" onclick={handleShare} title="Copy share link" aria-label="Share link">
					{#if shareCopied}✓{:else}⎘{/if}
				</button>
			{/if}
			<button class="panel-close" onclick={handleClose} aria-label="Close panel">✕</button>
		</div>
	</div>

	{#if panel.content}
		{#if focus.key === 'character'}
			<div class="panel-body"><ContactForm /></div>
		{:else}
			<!-- eslint-disable-next-line svelte/no-at-html-tags -->
			<div class="panel-body">{@html panel.content.html}</div>
		{/if}
	{/if}
</div>

<!-- Backdrop -->
{#if panel.open}
	<button class="panel-backdrop" onclick={handleClose} aria-label="Close panel" tabindex="-1"></button>
{/if}

<style>
	.panel {
		position: fixed;
		top: 50%;
		right: -440px;
		transform: translateY(-50%);
		width: min(400px, 90vw);
		max-height: 80vh;
		overflow-y: auto;
		background: rgba(8, 10, 26, 0.88);
		backdrop-filter: blur(24px) saturate(1.4);
		border: 1px solid rgba(124, 106, 247, 0.22);
		border-radius: 20px;
		padding: 20px 22px 22px;
		z-index: 20;
		transition: right 0.4s cubic-bezier(0.34, 1.42, 0.64, 1);
		color: #e8eeff;
		box-shadow: 0 0 0 1px rgba(255,255,255,0.04) inset, 0 32px 80px rgba(0,0,0,0.7), 0 0 40px rgba(124,106,247,0.08);
	}

	.panel.open { right: 20px; }

	.panel-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		margin-bottom: 18px;
	}

	.panel-actions {
		display: flex;
		align-items: center;
		gap: 6px;
	}

	.panel-share, .panel-close {
		background: rgba(255,255,255,0.06);
		border: 1px solid rgba(255,255,255,0.1);
		color: rgba(255,255,255,0.5);
		font-size: 15px;
		cursor: none;
		padding: 4px 9px;
		border-radius: 8px;
		transition: color 0.15s, background 0.15s, border-color 0.15s;
		line-height: 1.4;
	}

	.panel-share:hover, .panel-close:hover {
		color: #fff;
		background: rgba(124,106,247,0.18);
		border-color: rgba(124,106,247,0.4);
	}

	.panel-title {
		font-size: 19px;
		font-weight: 700;
		margin: 0;
		background: linear-gradient(135deg, #c8d8ff 0%, #a090f0 100%);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
	}

	.panel-body {
		font-size: 14px;
		line-height: 1.7;
	}

	/* Dynamic content styles (generated by ui.svelte.ts) */
	:global(.panel-cards) {
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	:global(.panel-card) {
		background: rgba(255 255 255 / 0.05);
		border-radius: 10px;
		padding: 14px 16px;
		border: 1px solid rgba(255 255 255 / 0.08);
	}

	:global(.panel-card h3) {
		margin: 0 0 6px;
		font-size: 15px;
		color: #a0c0ff;
	}

	:global(.panel-card p) {
		margin: 0 0 10px;
		color: rgba(255 255 255 / 0.7);
		font-size: 13px;
	}

	:global(.case-study-link) {
		display: inline-block;
		margin-top: 8px;
		font-size: 11px;
		font-weight: 600;
		color: #7c6af7;
		text-decoration: none;
		letter-spacing: 0.04em;
		transition: color 0.15s;
	}
	:global(.case-study-link:hover) { color: #a090f0; text-decoration: underline; }

	:global(.tech-tags) {
		display: flex;
		flex-wrap: wrap;
		gap: 6px;
	}

	:global(.tech-tags span) {
		font-size: 11px;
		padding: 3px 8px;
		border-radius: 20px;
		background: rgba(100 130 255 / 0.2);
		color: #99bbff;
		border: 1px solid rgba(100 130 255 / 0.3);
	}

	:global(.skill-group) {
		margin-bottom: 20px;
	}

	:global(.skill-group h3) {
		font-size: 12px;
		letter-spacing: 0.1em;
		text-transform: uppercase;
		color: rgba(255 255 255 / 0.4);
		margin: 0 0 10px;
	}

	:global(.skill-group ul) {
		margin: 0;
		padding: 0;
		list-style: none;
		display: flex;
		flex-wrap: wrap;
		gap: 8px;
	}

	:global(.skill-group li) {
		font-size: 13px;
		padding: 4px 12px;
		border-radius: 20px;
		background: rgba(255 255 255 / 0.07);
		border: 1px solid rgba(255 255 255 / 0.1);
	}

	:global(.about-panel h2) {
		margin: 0 0 4px;
		font-size: 22px;
	}

	:global(.about-panel .role) {
		color: #7799ff;
		font-size: 14px;
		margin: 0 0 16px;
	}

	:global(.facts) {
		margin: 16px 0 0;
		padding: 0;
		list-style: none;
		display: flex;
		flex-direction: column;
		gap: 6px;
	}

	:global(.facts li::before) {
		content: '▸ ';
		color: #7799ff;
	}

	:global(.contact-panel ul) {
		margin: 0;
		padding: 0;
		list-style: none;
		display: flex;
		flex-direction: column;
		gap: 12px;
	}

	:global(.contact-panel li) {
		display: flex;
		gap: 12px;
	}

	:global(.contact-panel strong) {
		min-width: 72px;
		color: rgba(255 255 255 / 0.45);
		font-size: 12px;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		padding-top: 1px;
	}

	:global(.contact-panel a) {
		color: #88aaff;
		text-decoration: none;
	}

	:global(.contact-panel a:hover) {
		text-decoration: underline;
	}

	:global(.available-badge) {
		display: inline-block;
		margin-bottom: 18px;
		padding: 4px 12px;
		border-radius: 20px;
		background: rgba(80 200 120 / 0.15);
		color: #80e8a0;
		border: 1px solid rgba(80 200 120 / 0.3);
		font-size: 12px;
		font-weight: 600;
	}

	.panel-backdrop {
		position: fixed;
		inset: 0;
		z-index: 19;
		background: transparent;
		border: none;
		cursor: default;
	}

	@media (max-width: 600px) {
		.panel {
			top: auto;
			bottom: -100vh;
			right: 0;
			left: 0;
			width: 100%;
			max-height: 65vh;
			border-radius: 20px 20px 0 0;
			transform: none;
			transition: bottom 0.35s cubic-bezier(0.34, 1.56, 0.64, 1);
		}

		.panel.open {
			right: 0;
			bottom: 0;
		}
	}
</style>
